spring:
  application:
    name: cholecystitis
  profiles:
    active: dev
  config:
    import:
      optional:configserver:http://192.168.1.23:8071
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always